### ISSUE TITLE
Published on npm?

### ISSUE THREAD

**Issue by layflags** [tcrowe/hyperapp-to-html#1]
I guess your project is not published on npm, right? The one I find there is https://www.npmjs.com/package/hyperapp-to-html from queckezz which doesn't work for me as a replacement for `hyperapp-server`. `hyperapp-server` has at least one issue, it renders the event handler code, e.g. `... onclick="function handleClick() { ...` which is what I wouldn't expect ;) Your lib doesn't have this issue 👍 

What do you think, do you want to publish your project on npm ... maybe under a different name, e.g. `hyperapp-to-string` or so?

**Comment by tcrowe** [comment]
Sorry @layflags the notifications were not on for this repo. I did not publish to npm. Was this repo working for you?

**Comment by tcrowe** [comment]
This one also provides a scheme for sending the state down to the client in the HTML then parsing it on the client.

**Comment by layflags** [comment]
Yes, it works for me. But I just prerender my html page during build and then use the Hydrator mixin: https://github.com/hyperapp/hyperapp/blob/master/docs/hydration.md. For now I just installed your lib via `yarn add tcrowe/hyperapp-to-html` directly from github. But would be nice to have a npm package :)

**Comment by tcrowe** [comment]
That's how I'm doing it too. I didn't know if anyone would need this. I thought most people were using it only on front end. 🤷‍♂️ 

PRs welcome if you find any glitches. We could also do it in ES6 if needed. I just tried to make it as simple as I could with good performance.

**Comment by tcrowe** [comment]
`hyperapp-stringify` does not exist. This could be renamed.

**Comment by layflags** [comment]
Sounds good! If you find some time ... thx!

**Comment by tcrowe** [comment]
https://github.com/tcrowe/hyperapp-stringify

`npm i hyperapp-stringify`

👌

**Comment by layflags** [comment]
Awesome 👍 Big thx @tcrowe !!!
